version: '3.8'

services:
  web:
    build: .
    command: gunicorn youtube_clone.wsgi:application --bind 0.0.0.0:8000 --reload
    volumes:
      - ./app/:/usr/src/app/
      - static_volume:/usr/src/app/staticfiles
    expose:
      - "8000"
    env_file:
      - ./env/.env
    depends_on:
      - db
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ./env/.env.db
    ports:
      - "5432:5432"
  nginx:
    build: ./images/nginx
    volumes:
      - static_volume:/usr/src/app/staticfiles
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  postgres_data:
  static_volume: